# Generated by Django 2.2.3 on 2019-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('password', models.CharField(max_length=1000)),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
